# Writes the public client config the static portal needs. These are NOT secrets
# (any browser hitting Cognito sees them), so the generated file is committed and
# served by GitHub Pages. Regenerated on every apply.
resource "local_file" "portal_config" {
  filename = "${path.module}/../portal/config.js"

  content = <<-EOT
    // GENERATED by Terraform (backend/portal-config.tf) — do not edit by hand.
    // Public client identifiers only; no secrets. Safe to commit and serve.
    window.__PORTAL_CONFIG__ = {
      region: ${jsonencode(var.region)},
      userPoolId: ${jsonencode(aws_cognito_user_pool.portal.id)},
      userPoolClientId: ${jsonencode(aws_cognito_user_pool_client.portal.id)},
      identityPoolId: ${jsonencode(aws_cognito_identity_pool.portal.id)},
      bucket: ${jsonencode(aws_s3_bucket.uploads.bucket)},
    };
  EOT
}
