// GENERATED by Terraform (backend/portal-config.tf) — do not edit by hand.
// Public client identifiers only; no secrets. Safe to commit and serve.
window.__PORTAL_CONFIG__ = {
  region: "eu-west-1",
  userPoolId: "eu-west-1_3f0nnxAj8",
  userPoolClientId: "6qtlgdqofegqfa736pfoalsin4",
  identityPoolId: "eu-west-1:4d3e6ee9-98f5-49ba-85c4-8eb2d0b05c21",
  bucket: "tpc-portal-user-uploads-4c411a4b",
};
